Update cy.yml

diff --git a/.github/workflows/cy.yml b/.github/workflows/cy.yml
--- a/.github/workflows/cy.yml
+++ b/.github/workflows/cy.yml
@@ -30,16 +30,16 @@ jobs:
         sudo docker run --rm ticsctests bash -c "bats ti-csc/utils/tests/unit/" || \
         (echo "Unit tests failed. Reviewing logs:" && exit 1)
 
-        - name: Run Integration Tests Inside Docker
-        if: always()  # Ensures this step runs no matter the status of previous steps
-        run: |
-          sudo docker run \
-            -v /usr/local/MATLAB/MATLAB_Runtime/R2024a:/usr/local/MATLAB/MATLAB_Runtime/R2024a \
-            -e LD_LIBRARY_PATH=/usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2024a/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2024a/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2024a/sys/java/jre/glnxa64/jre/lib/amd64 \
-            --rm ticsctests bash -c "\
-              chmod +x /ti-csc/utils/tests/integration/test_analyzerIT.sh && \
-              /ti-csc/utils/tests/integration/test_analyzerIT.sh || \
-              (echo 'Integration tests failed. Reviewing logs:' && exit 1)"
+    - name: Run Integration Tests Inside Docker
+      if: always()  # Ensures this step runs no matter the status of previous steps
+      run: |
+        sudo docker run \
+          -v /usr/local/MATLAB/MATLAB_Runtime/R2024a:/usr/local/MATLAB/MATLAB_Runtime/R2024a \
+          -e LD_LIBRARY_PATH=/usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2024a/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2024a/sys/os/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/R2024a/sys/java/jre/glnxa64/jre/lib/amd64 \
+          --rm ticsctests bash -c "\
+            chmod +x /ti-csc/utils/tests/integration/test_analyzerIT.sh && \
+            /ti-csc/utils/tests/integration/test_analyzerIT.sh || \
+            (echo 'Integration tests failed. Reviewing logs:' && exit 1)"
 
     - name: Cleanup Docker
       if: always()  # Ensures cleanup happens even if prior steps fail
