Added unit test for shell script

diff --git a/.github/workflows/cy.yml b/.github/workflows/cy.yml
--- a/.github/workflows/cy.yml
+++ b/.github/workflows/cy.yml
@@ -74,6 +74,9 @@ jobs:
       run: |
         docker run --rm ticsctests bash -c "simnibs_python -m pytest ti-csc/utils/tests/unit" || \
         (echo "Unit tests failed. Reviewing logs:" && exit 1)
+        docker run --rm ticsctests bash -c "bats ti-csc/utils/tests/unit/" || \
+        (echo "Unit tests failed. Reviewing logs:" && exit 1)
+
 
     - name: Run Integration Tests Inside Docker
       run: |
