Update cy.yml

diff --git a/.github/workflows/cy.yml b/.github/workflows/cy.yml
--- a/.github/workflows/cy.yml
+++ b/.github/workflows/cy.yml
@@ -30,7 +30,13 @@ jobs:
                 bats /ti-csc/utils/tests/unit/"
             - name: Running integration tests
               run: |
-                docker run -v /usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.24.1:/usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.25.1 --rm ticsctests bash /ti-csc/utils/tests/integration/test_analyzerIT.sh
+                docker run \
+                  -v /usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.24.1:/usr/local/MATLAB/MATLAB_Runtime/R2024a/runtime/glnxa64/libmwmclmcrrt.so.25.1 \
+                  --rm ticsctests bash -c "\
+                  chmod +x /ti-csc/utils/tests/integration/test_analyzerIT.sh && \
+                  chmod +x /ti-csc/analyzer/field-analysis/process_mesh_files && \
+                  /ti-csc/utils/tests/integration/test_analyzerIT.sh || \
+                  (echo 'Integration tests failed. Reviewing logs:' && exit 1)"
             - name: Cleanup Docker
               if: always()  # Ensures cleanup happens even if prior steps fail
               run: |
