Added step to run analyzer, and removed unused elements

diff --git a/.github/workflows/cy.yml b/.github/workflows/cy.yml
--- a/.github/workflows/cy.yml
+++ b/.github/workflows/cy.yml
@@ -32,9 +32,11 @@ jobs:
 
     - name: Run Integration Tests Inside Docker
       run: |
-        docker run --rm ticsctests bash -c "chmod +x ti-csc/utils/tests/integration/test_analyzerIT.sh" || \
-        (echo "Integration tests failed. Reviewing logs:" && exit 1)
-
+        docker run --rm ticsctests bash -c "\
+        chmod +x ti-csc/utils/tests/integration/test_analyzerIT.sh && \
+        ti-csc/utils/tests/integration/test_analyzerIT.sh || \
+        (echo 'Integration tests failed. Reviewing logs:' && exit 1)"
+      
     - name: Cleanup Docker
       if: always()
       run: |
