Added permissions and error handling for running unit tests

diff --git a/.github/workflows/cy.yml b/.github/workflows/cy.yml
--- a/.github/workflows/cy.yml
+++ b/.github/workflows/cy.yml
@@ -25,9 +25,10 @@ jobs:
               run: docker build --pull --rm -f "Dockerfile" -t ticsctests:latest "."
             - name: Running unit tests
               run: |
-                docker run --rm ticsctests:latest sh -c "
-                simnibs_python -m pytest /ti-csc/utils/tests/unit/ && 
-                bats /ti-csc/utils/tests/unit/"
+                sudo docker run --rm ticsctests bash -c "simnibs_python -m pytest ti-csc/utils/tests/unit" || \
+                (echo "Python unit tests failed. Reviewing logs:" && exit 1)
+                sudo docker run --rm ticsctests bash -c "bats ti-csc/utils/tests/unit/" || \
+                (echo "Bash unit tests failed. Reviewing logs:" && exit 1
             - name: Running integration tests
               run: |
                 docker run \
